#:schema node_modules/wrangler/config-schema.json
name = "worldcup-2026"
pages_build_output_dir = "."
compatibility_date = "2026-06-13"

[[kv_namespaces]]
binding = "VOTE_KV"
id = "3db593e2ba69422d8d10aca33e6e7bc2"
